{
 "title": "Ads Monitor - Budgets",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "account_name",
    "label": "Account:",
    "query": {
     "query": "label_values(googleads_mapping_info, account_name)"
    }
   },
   {
    "name": "campaign_name",
    "label": "campaign_name",
    "query": {
     "query": "label_values(googleads_mapping_info{account_name=~\"$account_name\"}, campaign_name)"
    }
   },
   { "name": "lookback_interval", "query": "5m,10m,15m,30m,1h,2h,6h" },
   {
    "name": "campaign_type",
    "query": {
     "query": "label_values(googleads_mapping_info, campaign_type)"
    }
   },
   { "name": "budget_spend_threshold", "label": "Budget Spend Threshold", "query": "0.5" },
   { "name": "top_n_entities", "query": "10,20,50,100" },
   { "name": "min_spend", "query": "0.1" }
  ]
 },
 "panels": [
  { "title": "Budgets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current spend $account_name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads:cost{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"})",
     "legendFormat": "cost"
    }
   ]
  },
  {
   "title": "Budget $account_name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads:campaigns:budgets{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"})",
     "legendFormat": "budget"
    }
   ]
  },
  {
   "title": "Cost / Budget $account_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(googleads:cost{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"})\n/\n  sum(googleads:campaigns:budgets{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"})",
     "legendFormat": "spend_share"
    }
   ]
  },
  {
   "title": "Predicted Cost / Budget $account_name in 1 hour",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(predict_linear(googleads:cost{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"}[3h], 3600))\n/\n  sum(googleads:campaigns:budgets{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"})",
     "legendFormat": "spend_share"
    }
   ]
  },
  {
   "title": "Cost / Budget",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum(googleads:cost{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"})\n/\n  sum(googleads:campaigns:budgets{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"})",
     "legendFormat": "spend_share"
    }
   ]
  },
  {
   "title": "Cost / Budget",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(\n  (\n        sum by (campaign_name, account_name) (googleads:cost{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"})\n      /\n        sum by (campaign_name, account_name) (googleads:campaigns:budgets{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"})\n    >\n      $budget_spend_threshold\n  )\n)",
     "legendFormat": "spend_share"
    }
   ]
  },
  {
   "title": "Predicted Cost / Budget",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(\n  (\n        sum by (campaign_name, account_name) (predict_linear(googleads:cost{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"}[3h], 3600))\n      /\n        sum by (campaign_name, account_name) (googleads:campaigns:budgets{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"})\n    >\n      $budget_spend_threshold\n  )\n)",
     "legendFormat": "predicted_spend"
    }
   ]
  }
 ]
}