{
 "title": "Ads Monitor  - Disapprovals",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "account_name",
    "label": "Account:",
    "query": {
     "query": "label_values(googleads_mapping_info, account_name)"
    }
   },
   {
    "name": "campaign_name",
    "label": "campaign_name",
    "query": {
     "query": "label_values(googleads_mapping_info{account_name=~\"$account_name\"}, campaign_name)"
    }
   },
   {
    "name": "ad_group_name",
    "label": "ad_group_name",
    "query": {
     "query": "label_values(googleads_mapping_info{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"}, ad_group_name)"
    }
   },
   { "name": "top_n_topics", "label": "Top N topics", "query": "5" }
  ]
 },
 "panels": [
  {
   "title": "% of non-approved ads",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_disapprovals_ad_count) / sum(googleads:accounts:ad_count) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of unreviewed ads",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_disapprovals_ad_count{review_status!=\"REVIEWED\"}) / sum(googleads:accounts:ad_count) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics with increased/descreased dissapprovals",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(topic) (deriv(googleads_disapprovals_ad_count[1h])) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(topic) (deriv(googleads_disapprovals_ad_count[1h])) < 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approval Statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(approval_status) (googleads_disapprovals_ad_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Review Statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(review_status) (googleads_disapprovals_ad_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(topk($top_n_topics, sum by(topic) (googleads_disapprovals_ad_count)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Topics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(topk($top_n_topics, sum by(topic) (googleads_disapprovals_ad_count)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of non-approved ads - $account_name - $campaign_name - $ad_group_name",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_disapprovals_ad_count  * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) / sum(googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of unreviewed ads  - $account_name - $campaign_name - $ad_group_name",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_disapprovals_ad_count{review_status!=\"REVIEWED\"} * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) / sum(googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}