{
 "title": "Ads Monitor - New Entities",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_name",
    "label": "Account:",
    "query": {
     "query": "label_values(googleads_mapping_info, account_name)"
    }
   },
   {
    "name": "campaign_name",
    "label": "campaign_name",
    "query": {
     "query": "label_values(googleads_mapping_info{account_name=~\"$account_name\"}, campaign_name)"
    }
   },
   {
    "name": "ad_group_name",
    "label": "ad_group_name",
    "query": {
     "query": "label_values(googleads_mapping_info{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"}, ad_group_name)"
    }
   },
   { "name": "lookback_interval", "query": "5m,10m,15m,30m,1h,2h,6h" },
   {
    "name": "network",
    "label": "network",
    "query": {
     "query": "label_values(googleads_impressions, network)"
    }
   },
   {
    "name": "campaign_type",
    "query": {
     "query": "label_values(googleads_mapping_info, campaign_type)"
    }
   },
   { "name": "spike_threshold", "label": "Spike Threshold", "query": "4" },
   { "name": "budget_spend_threshold", "label": "Budget Spend Threshold", "query": "0.5" },
   { "name": "top_n_entities", "query": "10,20,50,100" },
   { "name": "min_spend", "query": "0.1" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Spikes and moving entities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New Ads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(googleads:ads:new)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New Ad Groups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(googleads:ad_groups:new)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New Campaigns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(googleads:campaigns:new)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DIsabled Ads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(googleads:ads:disabled)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DIsabled Ad Groups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(googleads:ad_groups:disabled)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DIsabled Campaigns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(googleads:campaigns:disabled)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New and paused entities entities ",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count by (account_name, campaign_name, ad_group_name, ad_group_id, ad_id) (googleads:ads:new)\n",
     "legendFormat": "new_ads"
    },
    {
     "expr": "count by (account_name, campaign_name, ad_group_name, ad_group_id) (googleads:ad_groups:new)\n",
     "legendFormat": "new_ad_groups"
    },
    {
     "expr": "count by (account_name, campaign_name) (googleads:campaigns:new)\n",
     "legendFormat": "new_ad_groups"
    },
    {
     "expr": "count by (account_name, campaign_name, ad_group_name, ad_group_id, ad_id) (googleads:ads:disabled)",
     "legendFormat": "disabled_ads"
    },
    {
     "expr": "count by (account_name, campaign_name, ad_group_name, ad_group_id) (googleads:ad_groups:disabled)",
     "legendFormat": "disabled_ad_groups"
    },
    {
     "expr": "count by (account_name, campaign_name) (googleads:campaigns:disabled)",
     "legendFormat": "disabled_campaigns"
    }
   ]
  }
 ]
}