{
 "title": "Ads Monitor Demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "account_name",
    "label": "Account:",
    "query": {
     "query": "label_values(googleads_mapping_info, account_name)"
    }
   },
   {
    "name": "campaign_name",
    "label": "campaign_name",
    "query": {
     "query": "label_values(googleads_mapping_info{account_name=~\"$account_name\"}, campaign_name)"
    }
   },
   {
    "name": "ad_group_name",
    "label": "ad_group_name",
    "query": {
     "query": "label_values(googleads_mapping_info{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\"}, ad_group_name)"
    }
   },
   { "name": "lookback_interval", "query": "5m,10m,15m,30m,1h,2h,6h" },
   {
    "name": "network",
    "label": "network",
    "query": {
     "query": "label_values(googleads_impressions, network)"
    }
   },
   { "name": "spike_threshold", "label": "Spike Threshold", "query": "0.1" }
  ]
 },
 "panels": [
  {
   "title": "Overall performance (Unfiltered)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Clicks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by () (googleads_clicks)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Impressions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (googleads_impressions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CTR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by() (googleads_clicks) / sum by()(googleads_impressions) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_cost) / sum(googleads_clicks)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by () (googleads_cost)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Conversions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (googleads_conversions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_cost) / sum(googleads_conversions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conversion Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_conversions) / sum(googleads_clicks)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Impressions",
   "type": "timeseries",
   "description": "Incremental impressions by 15 minutes for all accounts",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(googleads_impressions) - sum(googleads_impressions offset $lookback_interval)",
     "legendFormat": "impressions"
    }
   ]
  },
  {
   "title": "Clicks",
   "type": "timeseries",
   "description": "Incremental clicks by 15 minutes for all accounts",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(googleads_impressions) - sum(googleads_impressions offset $lookback_interval)",
     "legendFormat": "clicks"
    }
   ]
  },
  {
   "title": "Conversions",
   "type": "timeseries",
   "description": "Incremental conversions for all accounts",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(googleads_conversions) - sum(googleads_conversions offset $lookback_interval)",
     "legendFormat": "conversions"
    }
   ]
  },
  {
   "title": "CTR",
   "type": "timeseries",
   "description": "CTR by 15 minutes for all accounts",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(googleads_clicks) / sum(googleads_impressions) * 100",
     "legendFormat": "ctr"
    }
   ]
  },
  {
   "title": "CPC",
   "type": "timeseries",
   "description": "CPC by 15 minutes for all accounts",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(googleads_cost) / sum(googleads_clicks)",
     "legendFormat": "cpc"
    }
   ]
  },
  {
   "title": "CPA",
   "type": "timeseries",
   "description": "CPA by 15 minutes for all accounts",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(googleads_cost) / sum(googleads_conversions)",
     "legendFormat": "cpa"
    }
   ]
  },
  {
   "title": "Filtered Performance  - Account(s): $account_name; Campaign(s): $campaign_name., AdGroup(s): $ad_group_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Impressions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(googleads_impressions * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) - sum(googleads_impressions offset $lookback_interval * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"})",
       "legendFormat": "impressions"
      }
     ]
    },
    {
     "title": "Clicks",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(googleads_clicks * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) - sum(googleads_clicks offset $lookback_interval * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"})",
       "legendFormat": "clicks"
      }
     ]
    },
    {
     "title": "Conversions",
     "type": "timeseries",
     "description": "Incremental conversions by 15 minutes interval",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(googleads_conversions * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) - sum(googleads_conversions offset $lookback_interval * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"})",
       "legendFormat": "conversions"
      }
     ]
    },
    {
     "title": "CTR",
     "type": "timeseries",
     "description": "Incremental conversions by $lookback_interval interval",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "googleads_clicks  * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"} / googleads_impressions  * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}",
       "legendFormat": "conversions"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Split Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network split cost",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (network) (googleads_cost * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "$network Spend $lookback_interval",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "sum (googleads_cost{network=\"$network\"} * on(ad_group_id) group_left(account_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\"})  - sum (googleads_cost{network=\"$network\"} offset $lookback_interval * on(ad_group_id) group_left(account_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\"})",
       "legendFormat": "cost"
      }
     ]
    },
    {
     "title": "$network Clicks $lookback_interval",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum (googleads_clicks{network=\"$network\"} * on(ad_group_id) group_left(account_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\"})  - sum (googleads_clicks{network=\"SEARCH\"} offset $lookback_interval * on(ad_group_id) group_left(account_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\"})",
       "legendFormat": "clicks"
      }
     ]
    },
    {
     "title": "Splikes by network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "repeat": "network",
     "targets": [
      {
       "expr": "sum without(ad_group_name, ad_group_id, instance, job) (googleads_cost * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count) / sum without(ad_group_name, ad_group_id, instance, job) (googleads_cost *  on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count offset $lookback_interval) > $spike_threshold",
       "legendFormat": "{{network}} - {{account_name}} - {{campaign_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 22, "x": 0, "y": 11 } }
   ]
  },
  { "title": "Approvals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "% of non-approved ads",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_disapprovals_ad_count) / sum(googleads:accounts:ad_count) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of unreviewed ads",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_disapprovals_ad_count{review_status!=\"REVIEWED\"}) / sum(googleads:accounts:ad_count) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approval Statuses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(approval_status) (googleads_disapprovals_ad_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Review Statuses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(review_status) (googleads_disapprovals_ad_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of non-approved ads - $account_name - $campaign_name - $ad_group_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_disapprovals_ad_count  * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) / sum(googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of unreviewed ads  - $account_name - $campaign_name - $ad_group_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(googleads_disapprovals_ad_count{review_status!=\"REVIEWED\"} * on(ad_group_id) group_left(account_name, campaign_name, ad_group_name) googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) / sum(googleads:ad_groups:ad_count{account_name=~\"$account_name\",campaign_name=~\"$campaign_name\",ad_group_name=~\"$ad_group_name\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(sum by(topic) (googleads_disapprovals_ad_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Topics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(topic) (googleads_disapprovals_ad_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Placements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Cost split by placement type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by(type) (googleads_placements_cost)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Placements by impressions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 9, "y": 49 },
   "targets": [
    {
     "expr": "topk(5, max_over_time(googleads_placements_impressions[60m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 5 Placements by impressions",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "topk(50, sum by(name, type) (googleads_placements_cost))",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}