{
 "title": "Ads Monitor Internal Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Number of API Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(gaarf_api_requests_count_total[1d]) -increase(gaarf_api_requests_count_total[1d] offset $__range)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Report fetching latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gaarf_report_fetching_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics export latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gaarf_query_export_time_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporting utulization",
   "type": "stat",
   "description": "Shows percentage of time gaarf_exporter exports set of queries during the allocated delay window",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gaarf_exporting_seconds / gaarf_delay_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporting utulization",
   "type": "timeseries",
   "description": "Shows percentage of time gaarf_exporter exports set of queries during the allocated delay window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gaarf_exporting_seconds / gaarf_delay_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of API Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(gaarf_api_requests_count_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total Number of API Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "increase(gaarf_api_requests_count_total[1d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}